default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["BOOKS_DATABASE_HOST"] %>
  port: <%= ENV["BOOKS_DATABASE_PORT"] %>
  username: <%= ENV["BOOKS_DATABASE_USERNAME"] %>
  password: <%= ENV["BOOKS_DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: books_development

test:
  <<: *default
  database: books_test
